### ISSUE TITLE
Generate languages.yaml

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2479]
https://github.com/coala/coala-bears/blob/master/.ci/generate_bear_requirements.py loads all bears and only generates `bear-requirements.yaml`.

It should provide more information in yaml format.

A very useful dataset to create is a mapping of languages to bears.

That will allow the list of languages to be generated by moban if we templatise README.md: https://github.com/coala/coala-bears/issues/2169

**Comment by aadilmehdis** [comment]
Hi @jayvdb, I would like to work on this issue. Could you please elaborate more on the issue?

**Comment by jayvdb** [comment]
This would need to wait until https://github.com/coala/coala-bears/pull/2446 is merged first, but that should be very soon.

`generate_bear_requirements.py` currently reads the Bear `DEPENDENCIES`.

Each Bear has a `LANGUAGES` property, which we could use to create a yaml file like:

```yaml
languages:
  - name: Python
    bears:
      - BanditBear
      - MypyBear
      - PEP8Bear
      - PEP8NotebookBear
      - PyCommentedCodeBear
      - PyDocStyleBear
      - PyFlakesBear
      - PyImportSortBear
      - PyLintBear
      - PyUnusedCodeBear
      - PycodestyleBear
      - PyromaBear
      - PythonPackageInitBear
      - RadonBear
      - VultureBear
      - YapfBear
  - name: CSS
    bears:
      - CSSAutoPrefixBear
      - CSSCombBear
      - CSSLintBear
      - StyleLintBear
      - PrettierLintBear
      - PHPCodeSnifferBear
      - SASSLintBear
      - SCSSLintBear
...
```
